@startuml
'https://plantuml.com/class-diagram
interface Interface1{
    opration1()
}

interface Interface2{
    opration2()
    opration3()
}

interface Interface3{
    opration4()
    opration5()
}


class A
class C
class B
class D

B ..|> Interface1
B ..|> Interface2

D ..|> Interface1
D ..|> Interface3


Interface1 <.. A
Interface2 <.. A

Interface1 <.. C
Interface3 <.. C


@enduml